version: '3'
services:
  api:
    container_name: api
    image: api
    ports:
      - 4001:4001
  client:
    container_name: client
    image: client
    ports:
      - 80:80
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
